### ISSUE TITLE
Crash in Celery Task when using auto_retry functionality

### ISSUE THREAD

**Issue by sque** [Workable/flask-log-request-id#21]
In case where a celery task is auto-retried, then the `flask-log-request-id` raises an exception at the stage of injecting the current request id.

```python
@celery.task(bind=True, autoretry_for=(Exception,))
def generic_div(self, a, b):
    """Simple function to divide two numbers"""
    logger.info('Called generic_div({}, {})'.format(a, b))
    return a / b
```

The above code will raise the following exception
```python
Traceback (most recent call last):
  File "/Users/konstantinos/Workspace/flask-log-request-id-issue/venv/lib/python3.6/site-packages/celery/app/task.py", line 685, in retry
    S.apply_async()
  File "/Users/konstantinos/Workspace/flask-log-request-id-issue/venv/lib/python3.6/site-packages/celery/canvas.py", line 221, in apply_async
    return _apply(args, kwargs, **options)
  File "/Users/konstantinos/Workspace/flask-log-request-id-issue/venv/lib/python3.6/site-packages/flask_log_request_id/extras/celery.py", line 24, in apply_async
    kwargs['headers'][_CELERY_X_HEADER] = request_id
TypeError: 'NoneType' object does not support item assignment
```

### Proposed solution
We need to add a second check if the `headers` argument is set to `None` and convert it to empty dictionary before injecting request-id header.

**Comment by sque** [comment]
Fixed by #22
